#!/bin/bash

dir=$1



if [ $# == 1 ];	then

	if [ -d $dir ]; then 

		cd "$dir" 

		iter=1
		
		for file in `ls -S *`
		do			
			if [ -x $file ]; then				
			echo "$file"
			mv "$file" "$file.$iter"
			let iter++
		fi
		done


	else
		echo "Not real Directory"
	fi
else
		echo "Wrong number of parameters"
fi